Migration/unittests for tokens
tlacloc/llc-daos pull request #5
Opened 2022-03-08 15:58 UTC by didiermis

I updated old Unit Tests from:
daoreg.dao.test.js
daoreg.token.test.js

2022-03-11 02:16 UTC, tlacloc commented on test/daoreg.dao.test.js
> +  })
Seems good to me 👍🏿 
Maybe just fixing the indentation

2022-03-11 02:29 UTC, tlacloc requested changes
Looks good 👍🏿 
The code is great! It looks a lot or work you did here.

In general all the changes are good, just some typos and fixes on tittles when the word 'you' is used.
Also the comment block of daoreg.offers

2022-03-11 02:29 UTC, tlacloc commented on test/daoreg.dao.test.js
> +	    table: 'daos',
this indentation looks kinda weird. But the code looks good 👍🏿

2022-03-11 02:29 UTC, tlacloc commented on test/daoreg.offers.test.js
> +/*
I think you forgot to toggle the comment in the whole test

2022-03-11 02:29 UTC, tlacloc commented on test/daoreg.token.test.js
> +  it('Issue the new token', async function () {
Nice!,
Maybe 'Create a new token and issue it' describe a little better the test

2022-03-11 02:29 UTC, tlacloc commented on test/daoreg.token.test.js
> +  it('You can not issue, token symbol is not valid', async function () {
Also, there is a lot of 'you' in the test.
I think it would look better if you call as actor as user
i.e. _user can not issue an invalid token_

2022-03-11 02:29 UTC, tlacloc commented on test/daoreg.token.test.js
> +  it('You need to create the token before use it', async function(){
same as above

2022-03-11 02:29 UTC, tlacloc commented on test/daoreg.token.test.js
> +  it('Issued tokens must be a number, not an string', async function(){
Here is a typo, it should be _Issued tokens must be a number, not a string_

2022-03-11 02:29 UTC, tlacloc commented on test/daoreg.token.test.js
> +  it('Please specify the quantity of issued tokens with 4 decimal places', async function(){
This is not a proper tittle for a test case.

2022-03-24 16:12 UTC, tlacloc requested changes
looks good! Just two small changes to be ready to go!

2022-03-24 19:05 UTC, didiermis commented on test/daoreg.token.test.js
> +const { AssertionError, fail } = require('assert')
I think i was trying to implement something but it never happened, i'll fix it.

2022-03-24 19:07 UTC, didiermis commented on test/daoreg.token.test.js
> +const { AssertionError, fail } = require('assert')
tbh, i think it comes from old test versions.

2022-03-24 21:32 UTC, tlacloc approved these changes
LGTM 👍🏿

2022-03-24 21:32 UTC, merged